# Generated by Django 6.0.1 on 2026-01-28 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_email_configuracao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='status',
            field=models.CharField(choices=[('NAO_ASSINADO', 'Nao assinado'), ('ASSINADO', 'Contrato assinado'), ('ASSINADO_DIGITALMENTE', 'Assinado digitalmente')], default='NAO_ASSINADO', max_length=30),
        ),
    ]
